### PR TITLE
Fix breaking image

### PR DESCRIPTION
**Pull request by nully0x**
# Description

In this PR, I fixed issue highlighted in  #INC-5312

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks nully0x, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by vanessa-cooper — APPROVED** [review]
Excellent job nully0x! You're now able to merge the PR.

**Comment by nully0x** [comment]
In the PR fix issue with #INC-5312

**Pull request merged**
